language: java
jdk:
  - oraclejdk8

sudo: required
install: true

services:
  - docker

addons:
  sonarqube:
    token:
      secure: "TZYoVVeRlexkDi9obtXYd3h9gwrPd6pZP0+DqzmDjM3k9ajlbQywBgGfaUGgktIy3U05qdqgyCns3janBohy43d2rm3a72hTyNsF52RK9zZZOSBhtnP3imTHlsIcxBhI2N7cOYShJrqD+Eaou9UjCybsoplSKXa9ZzQ9q85MaALMOY691wcGRxst0d47ACLpS45THKhqporj8v+VdvWGlroT2x2gm1AF+glqcavSqkyxnVxIUW7I9AlhCSEaASxm+yHYRr2ialQ9s0kyvEZhHmafEvGCuXcktO72ZJtoxeSTfPLEySAMj73EaZOCmjxx0RrNChbF727TKuEfncIC8PcHwedvYOq6vJDnikjnBD5oK9Ob4BhhzPWNSWR28CEX/tD8hDgylnSObabf0E+WRSj5XsHn/vWetx+1sp/p89KYZjyBGFwQsG0wNeCBsEpHG7Qj7fpsy+Dn9tVYrj3RvMZ1kKa+V/j/pr0x732URlODW+3QmhLNfcdmKDTOLPpPmi7zwA94ZPdBVYhYJqjcpnMEgveyRNRMOnsG96Uz4PAS/lTq5K8mCt7Fg+UFZ0XnA1QuoiwzAoq2U3qbQWN1JIpBUkxKe9jfEPqnaY8u2JSbokpKuzmrkw02IbqWGkxVDXGlJuTVjQNluYg2fEBBarW3EPROsfqsQo+ZaXtvIUw="

cache:
 directories:
 - '$HOME/.m2/repository'
 - '$HOME/.sonar/cache'

script:
- mvn -f chirper/pom.xml clean verify -Pjacoco sonar:sonar coveralls:report
