language: java
jdk:
  - oraclejdk8

sudo: false
install: true

cache:
 directories:
 - '$HOME/.m2/repository'
 - '$HOME/.sonar/cache'

script:
- mvn -f chirper/pom.xml clean verify -Pjacoco sonar:sonar coveralls:report
